### ISSUE TITLE
Only one building animation is played when multiple animations are imported

### ISSUE THREAD

**Issue by SpagoAsparago** [kingdom-of-ds-hacking/CTRMapV#3]
Video of the issue: 
https://github.com/kingdom-of-ds-hacking/CTRMapV/assets/57636185/ebe1312c-6f97-43eb-9761-3f34e01d2966

I couldn't figure out how to export a Blender DAE with multiple animations to show up in the building editor, so I imported it first in Creative Studio, added both closing and opening door animations manually to it, then exported the new DAE and imported it to the building editor.

Then I set up the building settings just like other existing door buildings, with each animation set having a different animation. The issue is that for some reason only one animation is being played, even if both are clearly present in the DAE as well as in the building settings as shown in the video.

DAE of the model with both animations:
[CustomDoor.zip](https://github.com/kingdom-of-ds-hacking/CTRMapV/files/11733714/CustomDoor.zip)
Sorry if this is something obviously wrong I did with Blender or Creative Studio.

**Comment by HelloOO7** [comment]
I may be dumb, but I'm having a hard time spotting the issue that you are describing (apart from the Open and Close animations being swapped, which looks intentional). As shown in your video, the door opens when you enter it (that's one animation) and then opens and closes when you walk out (that's two). Is that not the intended behavior?

Edit: As for importing multiple animations, you should be able to import them individually using the import button after selecting a slot in the prop settings. CreativeStudio should not be required as far as I remember.

**Comment by SpagoAsparago** [comment]
The door opening animation is supposed to slide to the left as seen in Creative Studio, the closing one slides to the right

In the video the door only slides to the right both when entering and leaving the building

It's not really an issue in this case, but I have made an elevator that has some more complex animations.

As for importing animations don't know how to explain it properly, but basically in the Blender hierarchy I could only have one "active" animation at a time, and when converting with apicula only one animation is imported even tho both animations exists in Blender. It might be because I know little about non-bone animations

**Comment by HelloOO7** [comment]
I am aware that the animation named "Open" slides to the left, however:

- the animation starts off-center and moves to the center, which would in reality animate a closing motion
- the animation is imported into the slot used for closing animations on regular doors. See f. e. 259: door_normal01 - the first animation slot is occupied by door_op, the second one by door_cl.

Thus, the open/close effect seems to work as intended, even though the animation names are swapped.

It's true that you can only export one animation in blender into one DAE file, however, you can export them into multiple DAE (or SMD) files and then import these individually. The editor will only read the animations and ignore the model part if they are imported into the slots with the import button (contrary to CS).

**Comment by SpagoAsparago** [comment]
Ah my bad I didn't realize there something wrong with my animation, you're right

Thanks again for your help
