### ISSUE TITLE
Building disappears

### ISSUE THREAD

**Issue by Cicciononciccione** [kingdom-of-ds-hacking/CTRMapV#6]
When i walk 6 steps right to a specific building it disappears. I changed the box_test, and it doesn't change anything. Also i'm not walking into a different map.
![image_2024-01-22_142731146](https://github.com/kingdom-of-ds-hacking/CTRMapV/assets/128183453/5cfb810a-9b3e-437a-9454-634b5462e8dd)

![image](https://github.com/kingdom-of-ds-hacking/CTRMapV/assets/128183453/2b736e72-4f09-41e3-847e-6efac24bb3ed)

**Comment by HelloOO7** [comment]
That does not tell me much. Can you use no$gba's VRAM viewer to analyze how the display list for the prop behaves when it's on screen and off screen as well as what the BOX_TEST call looks like when the prop is rendered properly?

**Comment by HelloOO7** [comment]
Closed due to inactivity.
